# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddedZoneDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tld', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=300)),
                ('added', models.DateField(verbose_name=b'date added')),
            ],
        ),
        migrations.CreateModel(
            name='Nameserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('assigned', models.DateField(verbose_name=b'date assigned')),
            ],
        ),
        migrations.CreateModel(
            name='RemovedZoneDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tld', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=300)),
                ('removed', models.DateField(verbose_name=b'date removed')),
                ('nameservers', models.ManyToManyField(related_name='removed_domains', to='domains.Nameserver')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='nameserver',
            unique_together=set([('name', 'assigned')]),
        ),
        migrations.AddField(
            model_name='addedzonedomain',
            name='nameservers',
            field=models.ManyToManyField(related_name='added_domains', to='domains.Nameserver'),
        ),
        migrations.AlterUniqueTogether(
            name='removedzonedomain',
            unique_together=set([('tld', 'name', 'removed')]),
        ),
        migrations.AlterUniqueTogether(
            name='addedzonedomain',
            unique_together=set([('tld', 'name', 'added')]),
        ),
    ]
