# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_addedmalwaredomain_removedmalwaredomain'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addedmalwaredomain',
            unique_together=set([('tld', 'name', 'added')]),
        ),
        migrations.AlterUniqueTogether(
            name='removedmalwaredomain',
            unique_together=set([('tld', 'name', 'removed')]),
        ),
    ]
