# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_auto_20161101_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoisQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=300)),
                ('registrar', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=20)),
                ('creation', models.DateField(verbose_name=b'date assigned')),
            ],
        ),
    ]
