# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_whoisquery'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='whoisquery',
            unique_together=set([('domain_name', 'creation', 'country', 'registrar')]),
        ),
    ]
